apiVersion: v1
kind: Pod
metadata:
  name: java-docker-pod
spec:
  containers:
  - name: java-docker-container
    image: 894704312282.dkr.ecr.us-east-1.amazonaws.com/java-docker-app:latest
    ports:
    - containerPort: 8080
  imagePullSecrets:
  - name: regcred
